# Generated by Django 2.2.4 on 2021-04-22 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='desc',
        ),
        migrations.AddField(
            model_name='show',
            name='description',
            field=models.TextField(default='Description*'),
        ),
        migrations.AlterField(
            model_name='show',
            name='network',
            field=models.CharField(default='Network*', max_length=255),
        ),
        migrations.AlterField(
            model_name='show',
            name='release_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='show',
            name='title',
            field=models.CharField(default='Title*', max_length=255),
        ),
    ]
